### ISSUE TITLE
No longer deploys - python2.7

### ISSUE THREAD

**Issue by dimikagi** [tstachlewski/serverless-survey#3]
This needs to be updated to use the latest version of python - it fails to deploy with:
Resource handler returned message: "The runtime parameter of python2.7 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.9) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: XXXXXXX, Extended Request ID: null)" (RequestToken: YYYYYYYY, HandlerErrorCode: InvalidRequest)

**Comment by tstachlewski** [comment]
Solved
